package LeetCodeSol.java;
/**
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 * 
 * @author caomi
 *
 */
public class FindDifference {
	public char findTheDifference(String s, String t) {
        int[] a = new int[26];
        int[] b = new int[26];
        char[] sArr = s.toCharArray();
        char[] tArr = t.toCharArray();
        for(int i = 0;i<sArr.length;i++){
            int index = (int)(sArr[i]-'a');
            a[index]++;
        }
        for(int i=0;i<tArr.length;i++){
            int index = (int)(tArr[i]-'a');
            b[index]++;
        }
        // find diff
        char result = 0;
        for(int i=0;i<26;i++){
            if(b[i]-a[i]==1) result= (char)('a'+i); 
        }
        return result;
    }
}
